### PR TITLE
Support for producers scheduling

### PR DESCRIPTION
**Pull request by blinkseb**
As title says. This will be useful to convert some analyzers into producers.

Note: this changes the python function Framework.schedule in order to add an additional named parameter. If we follow our proposed guideline, this means we should bump major version. Do we all agree on that?

### CODE REVIEW

**Comment by OlivierBondu** [comment]
yes, I would agree, but we would need to decide how and when we tag a new version, not every commit I guess ?

**Comment by blinkseb** [comment]
Indeed, we need a release strategy :) Tagging every commit is IMO a non-sense. Maybe we can imagine tagging every week, or before a new campaign?

**Comment by OlivierBondu** [comment]
yep, every beginning on the week to tentatively rerun end-to-end things for Friday ?
or every new JSON file ?

**Comment by delaere** [comment]
Note that you don't need to tag for that (weekly reruns), as every git commit is a full snapshot. You can even search the state by date. So I would limit tags to notable points: presentations, drafts, etc.

**Pull request merged**
