### PR TITLE
Add support for fat jets when redoing JEC

### PR DESCRIPTION
**Pull request by blinkseb**
This is mainly for the ZA guys, but can be useful for everyone if we go for boosted.

### CODE REVIEW

**Comment by OlivierBondu** [comment]
Looks like an update of the ref trees is needed !

**Comment by blinkseb** [comment]
Ah crap, I though fat jets were not in any trees. So indeed, update is needed!

**Comment by blinkseb** [comment]
Trees updated!

**Comment by OlivierBondu** [comment]
Thanks !

**Pull request merged**
