### PR TITLE
Use 15 GeV jets to compute Type-1 MET

### PR DESCRIPTION
**Pull request by blinkseb**
As title says. This is the new MET recommendation.

### CODE REVIEW

**Comment by OlivierBondu** [comment]
the branch is out of date, for some reason, can you rebase ?

**Comment by blinkseb** [comment]
Yes it became out of date as soon as you merged the other PR. I'll rebase

**Comment by blinkseb** [comment]
Tried the 'Update branch' button :smile: Now let's wait for the build...

**Comment by OlivierBondu** [comment]
ah sorry, did not check the order !

**Pull request merged**
