### PR TITLE
Muons SF update

### PR DESCRIPTION
**Pull request by OlivierBondu**
This PR features several changes and updates, only about muons:
- the old trigger SF files hanging in the `ScaleFactor` directory have been deleted (aka: ZA-analyzers please take note and sync with the rest of us :smile: )
- the previous Muon SF files and source files have been deleted
- the new source files from both Muon POG and HWW have been added to `sources/muons`
- a new script `mergeEfficiencyFiles.py` is here to help merging the files from HWW which provides separately files for data and MC
- the old script `convertEGammaTxtFiles.py` to convert such files into FW format has been renamed (→ `convertEffTxtFileToSF.py`
- all new SF json files have been added to the framework `MuonsProducer.py`

Note: the HWW SF are now run-dependent as discussed in https://github.com/cp3-llbb/Framework/issues/196, but note that the run ranges provided are not in sync with Run2016X data-taking eras (:unamused:)

please review, I'll cross fingers that there is no typo hiding somewhere :wink:  I'll update the ref trees for merging only if I receive :+1:'s....

### CODE REVIEW

**Comment by blinkseb** [comment]
Thanks a lot! I think we are missing tracking SF for muons:

> Please also remind to include muon tracking specific SFs covering HIP inefficiencies on mere track reconstruction, as from here (https://twiki.cern.ch/twiki/bin/view/CMS/MuonReferenceEffsRun2#Tracking_efficiency_provided_by)

**Comment by OlivierBondu** [comment]
oops, I'll add them right away

in the meantime, some validation plots are available on ingrid at `/home/fynu/obondu/scratch/Higgs/CMSSW_8_0_19/src/cp3_llbb/CommonTools/scripts`

as a SF non-expert, they look more or less ok... but perhaps we should consider adding the x-coverage on the TProfile:s

**Comment by blinkseb** [comment]
Thanks for the plots, nothing suspicious after a quick look!

**Comment by OlivierBondu** [comment]
PR updated with tracking SF, along with README and extraction script for the provided rootfile

**Comment by blinkseb** [comment]
Thanks a lot looks good! However, I just noticed here [1] that we use the absolute value of eta for the muon SFs, but tracking ones are specified using non-absolute values... Not sure if it's relevant or not.

[1] https://github.com/cp3-llbb/Framework/blob/CMSSW_8_0_6p/src/MuonsProducer.cc#L46

**Comment by OlivierBondu** [comment]
checking with Hugues (muon POG) the original files contain:
- 1D integrated in pt vs eta
- 1D integrated in eta vs pt
- 2D pt vs abseta
  and 'usually' the 2D ones are the best, and in this case they are the ones we are taking

it just appears that the tracking study is uncorrelated with all that POG work and provides SF with a different binning

not sure how to detect either case automatically...  do you have suggestions ?

**Comment by blinkseb** [comment]
We should probably at some point extend the format to specify which variable is expected in X or Y, but way beyond the scope of the PR. Looking at the numbers, taking eta or |eta| won't change much anyway...

**Comment by OlivierBondu** [comment]
ok, adding this to the list of issues / features wanted then

I'll update the ref trees

**Comment by blinkseb** [comment]
Thanks, I'll try to do it today. Don't forget to rebase too, your branch seems out of date :)

**Comment by OlivierBondu** [comment]
rebased and squashed, ref trees updated

**Comment by blinkseb** [comment]
Thanks a lot!

**Comment by OlivierBondu** [comment]
for reference: partly addresses https://github.com/cp3-llbb/Framework/issues/183

**Pull request merged**
