### PR TITLE
Make packed particles branches transient

### PR DESCRIPTION
**Pull request by blinkseb**
Forward-port of #85

### CODE REVIEW

**Comment by swertz** [comment]
You mean packed?

**Comment by blinkseb** [comment]
Yes sorry, I just forward port the commit of #85 which is wrong too

**Comment by swertz** [comment]
Check failed because of 

```
++ git fetch blinkseb
error: RPC failed; result=18, HTTP code = 200
fatal: The remote end hung up unexpectedly
```

Since #85 was OK I think this can be merged as well?

**Comment by blinkseb** [comment]
Yep you can merge!

**Pull request merged**
