### PR TITLE
Save cMVAv2 b-tag discriminant

### PR DESCRIPTION
**Pull request by blinkseb**
Save cMVAv2 b-tag discriminant.

Note: scale-factors still need to be included

### CODE REVIEW

**Comment by OlivierBondu** [comment]
It seems that (as expected) an update of the ref trees is needed.. but the actual jenkins output is weirder, it mentions some branches both in `found in output tree but not in the reference tree` AND in `found in reference tree but not in output tree`, is there an ordering condition when looking for difference between trees ?

**Comment by blinkseb** [comment]
Looks like the debug output is buggy, I'll look at it

**Comment by blinkseb** [comment]
Fixing the bug leads to the following error:

```
Branches found in reference tree but not in output tree:

Branches found in output tree but not in the reference tree:
  fatjet_pfCombinedMVAV2BJetTags
  fatjet_softdrop_pfCombinedMVAV2BJetTags
  fatjet_softdrop_puppi_pfCombinedMVAV2BJetTags
  jet_pfCombinedMVAV2BJetTags

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Much more logical :)

**Comment by OlivierBondu** [comment]
Thanks !

**Pull request merged**
