### PR TITLE
Bug fixes on b-tagging scale-factors evaluation

### PR DESCRIPTION
**Pull request by blinkseb**
B-tagging scale-factors are provided as TFormula, which we should evaluate with the jet pt to obtain the SF. These SFs are valid only for a given pt range. This PR makes sure we don't evaluate the SFs using a pt which is non valid (ie, outside the range).

I also fixed the validity range of the discriminant. It's by default between 0 and 1 inside the CSV file, but it's not correct since the discriminant can be negative. It has not real effect since the formula *does not* depend on the discriminant value, but any jet with a discriminant outside the range would cause the error to be double (standard treatment). I put arbitrarly -100 - 100 to be safe

--

Based over #230 . Do not merge before #230 is merged and this rebased.

### CODE REVIEW

**Comment by blinkseb** [comment]
Reference trees updated

**Comment by swertz** [comment]
Good to go too?

**Comment by blinkseb** [comment]
Let me rebase first :)

**Comment by blinkseb** [comment]
Done :+1: This should be good to merge, no need to wait for jenkins

**Pull request merged**
