### PR TITLE
[76X] Massive port of PR

### PR DESCRIPTION
**Pull request by blinkseb**
This is a port of all PR listed in #135, ~~expect #145 because it's not merged yet~~ (#145 is included as well). I was too lazy to create many PRs so I grouped everything into the one :smile:

### CODE REVIEW

**Comment by OlivierBondu** [comment]
Jenkins isn't happy:

```
----- Begin Fatal Exception 10-Feb-2016 09:57:23 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Validating configuration of module: class=SmearedPATJetProducer label='slimmedJetsSmeared'
Exception Message:
In the configuration, parameter "variation" is defined as an untracked int32.
It should be tracked.
----- End Fatal Exception -------------------------------------------------
Failure using /var/jenkins/workspace/Framework/CMSSW/CMSSW_7_6_3_patch2/src/cp3_llbb/Framework/test/unit_tests_mc.py: status 73
status = 18688
```

**Comment by blinkseb** [comment]
Ah good I was afraid it would not be catched! Fixing it right now

**Comment by OlivierBondu** [comment]
talking about jenkins, could we change the retrigger phrase to `please test` as CMSSW ? I never can remember the proper sentence :)

**Comment by blinkseb** [comment]
I'll see what I can do :+1:

**Comment by blinkseb** [comment]
@OlivierBondu Should be ok. Magic phrase is now `please test`

**Comment by OlivierBondu** [comment]
thanks !

**Comment by blinkseb** [comment]
I've added #145 and hopefully fixed unit tests, let's see

**Comment by OlivierBondu** [comment]
thanks !

**Pull request merged**
