### PR TITLE
Fix access to subjet b-tagging

### PR DESCRIPTION
**Pull request by blinkseb**
There's no prefix to add to access b-tagging information.

@AlexandreMertens Can you test your code with this PR?

### CODE REVIEW

**Comment by AlexandreMertens** [comment]
After ~1000 events, I got this error:
----- Begin Fatal Exception 24-Nov-2015 15:32:16 CET-----------------------
An exception of category 'StdException' occurred while
   [0] Processing run: 1 lumi: 52334 event: 13070604
   [1] Running path 'p'
   [2] Calling event method for module ExTreeMaker/'framework'
Exception Message:
A std::exception was thrown.
vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
----- End Fatal Exception -------------------------------------------------

I am using this simple code to test:

  for(uint16_t ifatjet = 0; ifatjet < fatjets.p4.size(); ifatjet++){
      for(uint16_t isubjet = 0; isubjet < fatjets.softdrop_subjets_p4[ifatjet].size(); isubjet++){
          float sj_csvv2 = fatjets.getSoftDropBTagDiscriminant(ifatjet, isubjet, m_jetCSVv2Name);

**Comment by blinkseb** [comment]
Ok strange it should work, I'll investigate a bit. Which input file are you using?

**Comment by AlexandreMertens** [comment]
I am using:

```
file:/nfs/scratch/fynu/swertz/CMSSW_7_4_15/src/cp3_llbb/TTAnalysis/test/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_miniAODv2_oneFile.root
```

Btw, I added a "try catch", maybe that there are some subjets on which the btag is not runned, but it is only of the per mille level... see:

```
Begin processing the 1st record. Run 1, Event 8496493, LumiSection 34019 at 24-Nov-2015 15:58:49.992 CET
Begin processing the 101st record. Run 1, Event 8496862, LumiSection 34020 at 24-Nov-2015 15:58:56.209 CET
Begin processing the 201st record. Run 1, Event 8497196, LumiSection 34021 at 24-Nov-2015 15:58:58.887 CET
Begin processing the 301st record. Run 1, Event 8497460, LumiSection 34022 at 24-Nov-2015 15:59:00.086 CET
Begin processing the 401st record. Run 1, Event 8499749, LumiSection 34031 at 24-Nov-2015 15:59:01.168 CET
Begin processing the 501st record. Run 1, Event 8500011, LumiSection 34032 at 24-Nov-2015 15:59:02.995 CET
Begin processing the 601st record. Run 1, Event 8500258, LumiSection 34033 at 24-Nov-2015 15:59:03.889 CET
Begin processing the 701st record. Run 1, Event 33711816, LumiSection 134981 at 24-Nov-2015 15:59:04.767 CET
Begin processing the 801st record. Run 1, Event 33712115, LumiSection 134982 at 24-Nov-2015 15:59:05.660 CET
Begin processing the 901st record. Run 1, Event 13070196, LumiSection 52333 at 24-Nov-2015 15:59:06.345 CET
Begin processing the 1001st record. Run 1, Event 13070483, LumiSection 52334 at 24-Nov-2015 15:59:07.851 CET
did not manage to get the btag discriminant of the subjets
did not manage to get the btag discriminant of the subjets
Begin processing the 1101st record. Run 1, Event 13070799, LumiSection 52335 at 24-Nov-2015 15:59:09.369 CET
Begin processing the 1201st record. Run 1, Event 13083142, LumiSection 52385 at 24-Nov-2015 15:59:10.281 CET
Begin processing the 1301st record. Run 1, Event 13083464, LumiSection 52386 at 24-Nov-2015 15:59:11.401 CET
Begin processing the 1401st record. Run 1, Event 13083797, LumiSection 52387 at 24-Nov-2015 15:59:12.242 CET
Begin processing the 1501st record. Run 1, Event 14757841, LumiSection 59089 at 24-Nov-2015 15:59:13.727 CET
Begin processing the 1601st record. Run 1, Event 14758160, LumiSection 59090 at 24-Nov-2015 15:59:14.496 CET
Begin processing the 1701st record. Run 1, Event 18583723, LumiSection 74409 at 24-Nov-2015 15:59:15.342 CET
Begin processing the 1801st record. Run 1, Event 18584044, LumiSection 74410 at 24-Nov-2015 15:59:16.062 CET
Begin processing the 1901st record. Run 1, Event 18584392, LumiSection 74411 at 24-Nov-2015 15:59:17.614 CET
did not manage to get the btag discriminant of the subjets
did not manage to get the btag discriminant of the subjets
Begin processing the 2001st record. Run 1, Event 18996076, LumiSection 76059 at 24-Nov-2015 15:59:18.463 CET
Begin processing the 2101st record. Run 1, Event 18996378, LumiSection 76060 at 24-Nov-2015 15:59:19.255 CET
Begin processing the 2201st record. Run 1, Event 18996681, LumiSection 76061 at 24-Nov-2015 15:59:20.147 CET
Begin processing the 2301st record. Run 1, Event 41101077, LumiSection 164569 at 24-Nov-2015 15:59:20.926 CET
Begin processing the 2401st record. Run 1, Event 41101430, LumiSection 164570 at 24-Nov-2015 15:59:23.456 CET
Begin processing the 2501st record. Run 1, Event 21316936, LumiSection 85353 at 24-Nov-2015 15:59:24.210 CET
Begin processing the 2601st record. Run 1, Event 21317214, LumiSection 85353 at 24-Nov-2015 15:59:24.964 CET
Begin processing the 2701st record. Run 1, Event 21364568, LumiSection 85543 at 24-Nov-2015 15:59:25.768 CET
Begin processing the 2801st record. Run 1, Event 21364882, LumiSection 85544 at 24-Nov-2015 15:59:26.649 CET
Begin processing the 2901st record. Run 1, Event 21365239, LumiSection 85545 at 24-Nov-2015 15:59:30.310 CET
Begin processing the 3001st record. Run 1, Event 43489643, LumiSection 174131 at 24-Nov-2015 15:59:31.038 CET
Begin processing the 3101st record. Run 1, Event 43489952, LumiSection 174132 at 24-Nov-2015 15:59:31.756 CET
Begin processing the 3201st record. Run 1, Event 43490271, LumiSection 174133 at 24-Nov-2015 15:59:32.647 CET
Begin processing the 3301st record. Run 1, Event 43744489, LumiSection 175151 at 24-Nov-2015 15:59:33.486 CET
Begin processing the 3401st record. Run 1, Event 43746836, LumiSection 175161 at 24-Nov-2015 15:59:35.096 CET
Begin processing the 3501st record. Run 1, Event 43747158, LumiSection 175162 at 24-Nov-2015 15:59:35.856 CET
Begin processing the 3601st record. Run 1, Event 43747441, LumiSection 175163 at 24-Nov-2015 15:59:36.677 CET
Begin processing the 3701st record. Run 1, Event 71247193, LumiSection 285273 at 24-Nov-2015 15:59:37.417 CET
Begin processing the 3801st record. Run 1, Event 71247520, LumiSection 285274 at 24-Nov-2015 15:59:39.465 CET
Begin processing the 3901st record. Run 1, Event 71247908, LumiSection 285275 at 24-Nov-2015 15:59:40.227 CET
Begin processing the 4001st record. Run 1, Event 44439114, LumiSection 177933 at 24-Nov-2015 15:59:40.887 CET
did not manage to get the btag discriminant of the subjets
did not manage to get the btag discriminant of the subjets
Begin processing the 4101st record. Run 1, Event 44449450, LumiSection 177975 at 24-Nov-2015 15:59:41.585 CET
Begin processing the 4201st record. Run 1, Event 44449758, LumiSection 177976 at 24-Nov-2015 15:59:43.579 CET
Begin processing the 4301st record. Run 1, Event 44450061, LumiSection 177977 at 24-Nov-2015 15:59:45.063 CET
Begin processing the 4401st record. Run 1, Event 44450385, LumiSection 177978 at 24-Nov-2015 15:59:45.750 CET
Begin processing the 4501st record. Run 1, Event 80300524, LumiSection 321521 at 24-Nov-2015 15:59:46.586 CET
Begin processing the 4601st record. Run 1, Event 80300865, LumiSection 321523 at 24-Nov-2015 15:59:47.339 CET
Begin processing the 4701st record. Run 1, Event 80301133, LumiSection 321523 at 24-Nov-2015 15:59:48.599 CET
Begin processing the 4801st record. Run 1, Event 45061284, LumiSection 180425 at 24-Nov-2015 15:59:50.935 CET
Begin processing the 4901st record. Run 1, Event 45061629, LumiSection 180426 at 24-Nov-2015 15:59:51.715 CET
```

**Comment by blinkseb** [comment]
Well, it's not a good practice to catch such exception, since it's obviously a coding error. According to the code, we should have either no b-tag at all, or a value for each jet, but something is obviously wrong here :)

**Comment by blinkseb** [comment]
@AlexandreMertens should be ok now! Can you test once more? thanks!

**Comment by AlexandreMertens** [comment]
Working fine, thanks a lot

**Comment by blinkseb** [comment]
Great :) Next time, please wait for jenkins to build the PR before merging ;)

**Pull request merged**
