### PR TITLE
add deepCSV SFs

### PR DESCRIPTION
**Pull request by alesaggio**
Adding Scale Factors for DeepCSV

### CODE REVIEW

**Review by OlivierBondu — APPROVED** [review]
Looks good to me, thanks !
Let's wait for the other PR to be merged to factorize the changes to the reference trees, but it looks good

**Comment by alesaggio** [comment]
https://github.com/cp3-llbb/Framework/pull/270/files#diff-a1ce3e72a6655012c2f076271533f7c3R104
with this statement we are actually double-counting. Only one algo name (either "pfDeepCSVJetTags:probb" or "pfDeepCSVJetTags:probbb") should be required, since the deepCSV is defined as the sum of the two.

**Comment by OlivierBondu** [comment]
tracked at https://github.com/cp3-llbb/Framework/issues/257

**Comment by alesaggio** [comment]
I think we are ready to go :)

**Comment by OlivierBondu** [comment]
please test

**Comment by OlivierBondu** [comment]
please test

**Comment by OlivierBondu** [comment]
please test

**Comment by OlivierBondu** [comment]
Thanks! the tests outputs are as expected (see below), can you update the corresponding reference trees ?
```
Branches found in reference tree but not in output tree:

Branches found in output tree but not in the reference tree:
  fatjet_sf_deepCSV_heavyjet_loose
  fatjet_sf_deepCSV_heavyjet_medium
  fatjet_sf_deepCSV_heavyjet_tight
  fatjet_sf_deepCSV_lightjet_loose
  fatjet_sf_deepCSV_lightjet_medium
  fatjet_sf_deepCSV_lightjet_tight
  jet_sf_deepCSV_heavyjet_loose
  jet_sf_deepCSV_heavyjet_medium
  jet_sf_deepCSV_heavyjet_tight
  jet_sf_deepCSV_lightjet_loose
  jet_sf_deepCSV_lightjet_medium
  jet_sf_deepCSV_lightjet_tight

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 is a Catch v1.3.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
Check if trees are equals
-------------------------------------------------------------------------------
/opt/app-root/jenkins/workspace/Framework/CMSSW/CMSSW_8_0_30/src/cp3_llbb/Framework/bin/testFrameworkOutput.cc:103
...............................................................................

/opt/app-root/jenkins/workspace/Framework/CMSSW/CMSSW_8_0_30/src/cp3_llbb/Framework/bin/testFrameworkOutput.cc:157: FAILED:
  CHECK( test_tree->GetNbranches() == n_branches )
with expansion:
  219 == 207

===============================================================================
test cases:     1 |     0 passed | 1 failed
assertions: 20146 | 20145 passed | 1 failed

Output file does not match reference file: status 1
status = 256

---> test Testcp3_llbbFramework had ERRORS
```

**Comment by OlivierBondu** [comment]
Thanks!

**Pull request merged**
