### PR TITLE
Correctly propagate JEC to MET

### PR DESCRIPTION
**Pull request by blinkseb**
The current code does not do what it's supposed to do unfortunately. The code is changed in order to correctly propagate the JEC to MET when redoing the JEC (ie, keeping only jet with pt > 15 GeV, skipping muons etc.)

I've checked that re-doing JEC on top of miniAOD using the same global tag leads to exactly the same pt spectrum for both MET & jets.

I'm pretty sure reference trees will need to be regenerated, but let's test jenkins with the new branch

### CODE REVIEW

**Comment by blinkseb** [comment]
please test

**Comment by blinkseb** [comment]
Reference trees updated.

**Comment by blinkseb** [comment]
6 min 3 sec to build and test :smile:

**Comment by OlivierBondu** [comment]
thanks !

**Pull request merged**
