### PR TITLE
Add very simple unit test to check that the framework is running

### PR DESCRIPTION
**Pull request by blinkseb**
This PR adds a way for Jenkins to actually run the framework and see if it's working or not.

For this, it uses CMSSW unit test integration that can be launched using ``scram b runtests``.

There's only a single test for the moment, running the framework without any analysis over a ttbar MC file, stored on afs (build-bot has not certificate :sob:). Others can be easily added, more code oriented using cppunit. We just need to find someone motivated to write those tests :smiley: 

Let's see if it works!

### CODE REVIEW

**Comment by blinkseb** [comment]
Status should be failed since the tests failed. Investigating.

**Comment by OlivierBondu** [comment]
Should we, for safety, add a simple unit test on data ?

**Comment by blinkseb** [comment]
Sure, we just need to put a small data file on afs. Was too lazy to do it :)

**Comment by blinkseb** [comment]
Everything's ok from my side.

**Comment by OlivierBondu** [comment]
merging then ! thanks !

**Pull request merged**
