### PR TITLE
Adding MC matching info for jets and leptons

### PR DESCRIPTION
**Pull request by OlivierBondu**

### CODE REVIEW

**Comment by OlivierBondu** [comment]
@blinkseb : any comment is welcome :smile:

**Comment by blinkseb** [comment]
I guess we can avoid code duplication by adding an additional argument to the `fill_candidate` method, like

````C++
template <typename T, typename U>
void fill_candidate(const T& p, const U* gen) {
}
```
And calling it with the right function call from the producers

**Comment by OlivierBondu** [comment]
mmm, yes, but what to do for other types depending on CandidatesProducer that don't have gen info (HLT for example?)

**Comment by blinkseb** [comment]
Passing ``nullptr`` should be enough?

**Comment by OlivierBondu** [comment]
refactored

**Pull request merged**
