### PR TITLE
Workaround for 'git cms-merge-topic <hash>'

### PR DESCRIPTION
**Pull request by pieterdavid**
I copied the few relevant lines from `git-cms-merge-topic`, and assumed we always take a commit. The tricky part is related to sparse-checkout (figuring out the merge base, and using that to update the sparse-checkout config, but the hard part is done by cms-sparse-checkout).
I also took the freedom to reduce the number of `git cms-checkdeps` calls to one, that saves a bit of printout.

### CODE REVIEW

**Comment by pieterdavid** [comment]
That was quick... too bad jenkins isn't using zsh instead of bash :(

**Comment by blinkseb** [comment]
Try changing the shebang of the script, it may help :)

**Comment by pieterdavid** [comment]
Thanks for the suggestion, but it sources the bootstrap script (with `. .../bootstrap_jenkins.sh`), so that doesn't help :-(, I'll check the jenkins config

**Comment by pieterdavid** [comment]
@cp3-llbb-bot : please test

**Comment by OlivierBondu** [comment]
Let's wait for @pieterdavid to have his look at the `cms-merge-topic` history before merging ?

**Comment by pieterdavid** [comment]
The log looks fine now :-) . For reference: this broke with [this change](https://github.com/cms-sw/cms-git-tools/commit/8748af1f498ddd4537c1dc3690dd091b81fe5bc7#diff-ad03cccb399865882a3703e23f8e105fR127) (12 December 2017) in git-cms-merge-topic, so release areas from before that should be fine.
I pushed another commit to use `git cms-init --upstream-only` which should save quite some time and printout (because it doesn't need to get all the old tags), let's wait for the tests and then it should be fine to merge

**Comment by pieterdavid** [comment]
@cp3-llbb-bot please test

**Comment by OlivierBondu** [comment]
Thanks !

**Pull request merged**
