### PR TITLE
Add support for objects systematics

### PR DESCRIPTION
**Pull request by blinkseb**
This PR superseeds #109. I re-include first the description of #109, then add some description of the new way to create the framework configuration

---

For each systematics, CMSSW modules are automatically added to the sequence to produce the systematically modified objects (shifted jets for example). For each newly added, a Framework producer is added, named like the nominal producer but with a postfix ('jets' -> 'jets_jecup').

Analyzers configurations using any of the nominal producers are cloned, and parameters are automatically updated to match the new producers. In order for this to work, your analyzer must have some parameters of type `string` or `InputTag` whose value the name of the producer. Only
analyzers having at least one parameter matching the name of a producer are cloned. A postfix is appended to the new named of the analyzer ('tt' -> 'tt_jecup'), and all the branches prefix also include the systematics postfix.

Right now, only JEC (JES) and JER are supported, but the system is generic enough to add more if they are one day needed.

This PR also includes a refactoring on how we create the framework configuration. Instead of a simple function, framework is now configured using a class `Framework`. You can see a working example in `test/TestConfigurationMC.py`. Typical usage is now

```
framework = Framework(isData, era, globalTag='GT')
```

Then you can use the framework instance to tweak parameters, and add analyzers or producers:

```
framework.addAnalyzer('test', cms.PSet(<config>))
framework.redoJEC()
```

Then, the last action is to actually create the configuration, using `Framework.create()`:

```
process = framework.create()
```

Using this class, systematics can be enabled using the `Framework.doSystematics()` methods, which accepts as arguments a list of systematics. Only `'jec'` and `'jer'` as supported for the moment.

Scheduling is no longer needed, and analyzers and producers will be executed in the order they are added.

There's some side effects of these changes, needed to allow an analyzer to be ran multiple time sequentially:
- registered categories are now prefixed with the same prefix as the analyzer. For example, if an analyzer using a prefix `tt_` registers a category `mumu`, the real name of the category will be `tt_mumu`. This is reflected in the tree as the names of all the branches will also be prefixed. Python scripts used for plotting will unfortunately need to be changed.
- This PR breaks all analysis configuration, so we'll need a major version bump.
- NoHF met is gone, since it was actually not used by any analysis here and simplify a bit the code.

Output example for TTAnalysis, once modified to read producers names from python and to use the new code:

```
CP3 llbb framework:
    - Running over simulation
    - global tag: 74X_mcRun2_asymptotic_v2
    - era: 25ns

[...]

Configuring framework for 'jer' systematics
    Adding new CMSSW module 'slimmedJetsJERUp' as 'jets_jerup' framework producer
    Adding new CMSSW module 'slimmedJetsJERDown' as 'jets_jerdown' framework producer
    Adding new CMSSW module 'slimmedMETsJERUp' as 'met_jerup' framework producer
    Adding new CMSSW module 'slimmedMETsJERDown' as 'met_jerdown' framework producer
    Cloning 'tt' analyzer to 'tt_jerup' to run over new collections
        Changing value of parameter tt.parameters.jetsProducer (string) from 'jets' to 'jets_jerup'
        Changing value of parameter tt.parameters.metProducer (string) from 'met' to 'met_jerup'
    Cloning 'tt' analyzer to 'tt_jerdown' to run over new collections
        Changing value of parameter tt.parameters.jetsProducer (string) from 'jets' to 'jets_jerdown'
        Changing value of parameter tt.parameters.metProducer (string) from 'met' to 'met_jerdown'

Configuring framework for 'jec' systematics
    Adding new CMSSW module 'slimmedJetsJECUp' as 'jets_jecup' framework producer
    Adding new CMSSW module 'slimmedJetsJECDown' as 'jets_jecdown' framework producer
    Adding new CMSSW module 'slimmedMETsJECUp' as 'met_jecup' framework producer
    Adding new CMSSW module 'slimmedMETsJECDown' as 'met_jecdown' framework producer
    Cloning 'tt' analyzer to 'tt_jecup' to run over new collections
        Changing value of parameter tt.parameters.jetsProducer (string) from 'jets' to 'jets_jecup'
        Changing value of parameter tt.parameters.metProducer (string) from 'met' to 'met_jecup'
    Cloning 'tt' analyzer to 'tt_jecdown' to run over new collections
        Changing value of parameter tt.parameters.jetsProducer (string) from 'jets' to 'jets_jecdown'
        Changing value of parameter tt.parameters.metProducer (string) from 'met' to 'met_jecdown'


Framework configuration done.
    Producers: gen_particles, event, hlt, jets, jets_jecdown, jets_jecup, jets_jerdown, jets_jerup, met, met_jecdown, met_jecup, met_jerdown, met_jerup, muons, electrons, vertices
    Analyzers: tt, tt_jecup, tt_jecdown, tt_jerup, tt_jerdown
```

### CODE REVIEW

**Comment by OlivierBondu** [comment]
what happened to the `redoJEC` configuration option ?

**Comment by OlivierBondu** [comment]
I'm running into the following error:

``` bash
[ingrid-ui1]: ~/Higgs/CMSSW_7_4_15/src/cp3_llbb/HHAnalysis/test(0)>cmsRun HHConfiguration.py

CP3 llbb framework:
    - Running over simulation
    - global tag: 74X_mcRun2_asymptotic_v2
    - era: 25ns

# Conditions read from  CMS_CONDITIONS  via FrontierProd 

Changing process name from 'PAT' to None...


Configuring framework for 'jer' systematics
    Adding new CMSSW module 'slimmedJetsJERUp' as 'jets_jerup' framework producer
    Adding new CMSSW module 'slimmedJetsJERDown' as 'jets_jerdown' framework producer
    Adding new CMSSW module 'slimmedMETsJERUp' as 'met_jerup' framework producer
    Adding new CMSSW module 'slimmedMETsJERDown' as 'met_jerdown' framework producer

Configuring framework for 'jec' systematics
    Adding new CMSSW module 'slimmedJetsJECUp' as 'jets_jecup' framework producer
    Adding new CMSSW module 'slimmedJetsJECDown' as 'jets_jecdown' framework producer
    Adding new CMSSW module 'slimmedMETsJECUp' as 'met_jecup' framework producer
    Adding new CMSSW module 'slimmedMETsJECDown' as 'met_jecdown' framework producer


Framework configuration done.
    Producers: gen_particles, event, hlt, jets, jets_jecdown, jets_jecup, jets_jerdown, jets_jerup, fat_jets, met, met_jecdown, met_jecup, met_jerdown, met_jerup, muons, electrons, vertices
    Analyzers: hh_analyzer

21-Jan-2016 18:17:38 CET  Initiating request to open file file:////storage/data/cms/store/user/brfranco/testFiles/TTTo2L2Nu_13TeV-powheg_RunIISpring15MiniAODv2_74X_mcRun2_asymptotic_v2-v1.root
21-Jan-2016 18:17:42 CET  Successfully opened file file:////storage/data/cms/store/user/brfranco/testFiles/TTTo2L2Nu_13TeV-powheg_RunIISpring15MiniAODv2_74X_mcRun2_asymptotic_v2-v1.root

filters: 

producers: 
 -> Adding producer 'gen_particles' of type 'gen_particles'
 -> Adding producer 'event' of type 'event'
 -> Adding producer 'hlt' of type 'hlt'
HLT configuration: 
 -> Runs: [0, 999999]
    - HLT_Mu17_TrkIsoVVL_(Tk)?Mu8_TrkIsoVVL_DZ_v.*
    - HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v.*
    - HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v.*
    - HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL_v.*
    - HLT_IsoMu27_v.*

 -> Adding producer 'jets' of type 'jets'
 -> Adding producer 'jets_jecdown' of type 'jets'
 -> Adding producer 'jets_jecup' of type 'jets'
 -> Adding producer 'jets_jerdown' of type 'jets'
 -> Adding producer 'jets_jerup' of type 'jets'
 -> Adding producer 'fat_jets' of type 'fat_jets'
 -> Adding producer 'met' of type 'met'
 -> Adding producer 'met_jecdown' of type 'met'
 -> Adding producer 'met_jecup' of type 'met'
 -> Adding producer 'met_jerdown' of type 'met'
 -> Adding producer 'met_jerup' of type 'met'
 -> Adding producer 'muons' of type 'muons'
 -> Adding producer 'electrons' of type 'electrons'
 -> Adding producer 'vertices' of type 'vertices'

analyzers: 
 -> Adding analyzer 'hh_analyzer'

Reading JEC parameters = Total from file = /nfs/home/fynu/obondu/Higgs/CMSSW_7_4_15/src/cp3_llbb/Framework/data/Systematics/Summer15_25nsV6_MC_UncertaintySources_AK4PFchs.txt.
Reading JEC parameters = Total from file = /nfs/home/fynu/obondu/Higgs/CMSSW_7_4_15/src/cp3_llbb/Framework/data/Systematics/Summer15_25nsV6_MC_UncertaintySources_AK4PFchs.txt.
21-Jan-2016 18:18:12 CET  Closed file file:////storage/data/cms/store/user/brfranco/testFiles/TTTo2L2Nu_13TeV-powheg_RunIISpring15MiniAODv2_74X_mcRun2_asymptotic_v2-v1.root
----- Begin Fatal Exception 21-Jan-2016 18:18:12 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=SmearedPATJetProducer label='slimmedJetsJERDown'
Exception Message:
MissingParameter: Parameter 'dRmaxGenJetMatch' not found.
----- End Fatal Exception -------------------------------------------------
```

I cannot see this `dRmaxGenJetMatch` anywhere ?
My configuration is at https://github.com/OlivierBondu/HHAnalysis/blob/refactor_systematics/test/HHConfiguration.py

**Comment by blinkseb** [comment]
It's a function of the class now, so just do

```
framework.redoJEC()
```

To enable it.
Le 21 janv. 2016 6:19 PM, "Olivier Bondu" notifications@github.com a
écrit :

**Comment by blinkseb** [comment]
It's probably because I forgot to mention the recipe changed. There's a new package to checkout to use the new JER facility. `dRmaxGenJetMatch` is an option of the old package. Sorry about that!

**Comment by blinkseb** [comment]
Also you will probably need to change the default process name from `None` to `PAT`. I'll anyway add a check in the code for it :)

**Comment by OlivierBondu** [comment]
whoops indeed, my bad, I missed the changes to the README :/

all seems to compile and run fine :) now getting a look at the output

**Comment by blinkseb** [comment]
I've updated with some bug fixes. I still need to add support for nominal JER

**Comment by OlivierBondu** [comment]
so from testing on our radion m650 signal sample, here is what I see for a test on 1000 events, with the candidate with tight lepton ID, loose btag, and highest csv sum jet combinatorics
- on the m_jj spectrum:
  - for JER up (red, 436 events) nominal (black, 438 events) and down (blue, 437 events): [hh_jj_m_jer.pdf](https://github.com/cp3-llbb/Framework/files/100883/hh_jj_m_jer.pdf)
  - for JEC up (red, 445 events) nominal (black) and down (blue, 432 events): [hh_jj_m_jec.pdf](https://github.com/cp3-llbb/Framework/files/100884/hh_jj_m_jec.pdf)
- for the total mass m_llmetjj (so including also the effect on met):
  - for JER up (red) nominal (black) and down (blue): [hh_llmetjj_m_jer.pdf](https://github.com/cp3-llbb/Framework/files/100893/hh_llmetjj_m_jer.pdf)
  - for JEC up (red) nominal (black) and down (blue): [hh_llmetjj_m_jec.pdf](https://github.com/cp3-llbb/Framework/files/100892/hh_llmetjj_m_jec.pdf)

so overall I would say everything behaves as expected, it's a big :+1: as far as I am concerned :)

to @sdevissc and @AlexandreMertens : any objection to merging ? Again this PR breaks current analysis configuration... but the changes are not hard to come around

**Comment by OlivierBondu** [comment]
(note: we miss one last commit from @blinkseb for nominal JER)

**Comment by AlexandreMertens** [comment]
hey, it should be fine with us

**Comment by blinkseb** [comment]
And it's done :) I've rebase the PR with the latest changes. Doing `framework.smearJets()` now does something. Once merged, smearing should be done by all analysis :)

**Comment by OlivierBondu** [comment]
thanks again !

**Pull request merged**
