### PR TITLE
Correctly propagate JEC to MET

### PR DESCRIPTION
**Pull request by blinkseb**
Backport of #179 for CMSSW 7.6.X. I bumped the minimum CMSSW version to 7.6.5 (hence the new branch)

### CODE REVIEW

**Comment by OlivierBondu** [comment]
the checks failed, it looks like an update of the reference trees is needed !

**Comment by blinkseb** [comment]
Yep I wanted to test if jenkins was working with the new branch :)

**Comment by blinkseb** [comment]
PR updated, let's see how it goes

**Comment by OlivierBondu** [comment]
Goes well, thanks !

**Pull request merged**
