### PR TITLE
updating egamma regression to v2

### PR DESCRIPTION
**Pull request by OlivierBondu**
Thanks to @RemKamal for the notice!

If I read correctly [Framework.py#L433-L441](https://github.com/cp3-llbb/Framework/blob/CMSSW_8_0_6p/python/Framework.py#L433-L441) this should be the only update needed

### CODE REVIEW

**Comment by pieterdavid** [comment]
cms-git question: does this mean we have to re-create the release area (and possibly move to 8_0_26?), or can this be applied on top of an existing one?

**Comment by OlivierBondu** [comment]
I could do the `cms-merge-topic` on top of my existing installation... no idea if that's the correct thing though

**Comment by blinkseb** [comment]
If the new branch was branched from the old one, re-running the `merge-topic` should just pull the latest changes, no need for a new release

**Comment by pieterdavid** [comment]
I don't see the old branch on github, but merge-topic goes fine and the merge commit looks ok as well, so I guess that's the case - thanks for explaining

**Comment by RemKamal** [comment]
Hello all,

I guess Fabrice already answered, but still for completeness, doing merge on top with v2 should do the work. 
This is the main Twiki:
https://twiki.cern.ch/twiki/bin/view/CMS/EGMRegression  
and Rafael recommends to check that we are up-to-date with the instructions, which also changed at some time.

Rami

**Comment by blinkseb** [comment]
Thanks :+1:

**Pull request merged**
