### PR TITLE
[74X] Validate Framework output during unit tests

### PR DESCRIPTION
**Pull request by blinkseb**
The tree produced by the framework is compared to a reference tree to
ensure that nothing changed.

This should allow to detect bugs like the one introduces recently on the scale-factors.

I put a do not merge label to check jenkins output tomorrow :)

### CODE REVIEW

**Comment by blinkseb** [comment]
With the new commit, validation must failed. Let's see...

**Comment by blinkseb** [comment]
```
/var/jenkins/workspace/Framework/CMSSW/CMSSW_7_4_15/src/cp3_llbb/Framework/bin/testFrameworkOutput.cc:118: FAILED:
  REQUIRE( test_tree->GetNbranches() == n_branches )
with expansion:
  153 == 150
```

I was not expecting this error, but why not :)

**Comment by BrieucF** [comment]
:p

**Comment by blinkseb** [comment]
Ok that's better:)

```
`/var/jenkins/workspace/Framework/CMSSW/CMSSW_7_4_15/src/cp3_llbb/Framework/bin/testFrameworkOutput.cc:96: FAILED:
  REQUIRE( ref_sha == test_sha )
with expansion:
  "993652dfa12b12b21d948ffe4e7fa5554a6ebf636758d5fb18e1bd32c84aea81"
  ==
  "fb6a2154d6dcc96a1a9bea09aa11a38331007f4ce6584c14f39bac36d618eb80"
with message:
  [Event 0] Checking branches jet_p4.fCoordinates.fPt of type
  ROOT::Math::PtEtaPhiE4D<float>
```

**Comment by OlivierBondu** [comment]
mmm,  but what if we decide to change the systematics or such, is it checking every branch content out there ?

**Comment by blinkseb** [comment]
It's just checking the output of the unit test configuration. If you decide to run systematics on this configuration, then yes, you have to update the tree. The same is true if you change the scale factors or stuff like that. And that's exactly the point : if you know something change and you are confident with this change, then you update the tree. Otherwise, the check will failed and a bug can be fixed :)

**Comment by OlivierBondu** [comment]
:+1:

**Comment by blinkseb** [comment]
Forgot to remove the do not merge label ... :)

**Pull request merged**
