### PR TITLE
[74X] Fix crash on non-LHE samples. Fix #149

### LINKED ISSUE #149: Crashes on QCD
Most probably following the merge of #147 

```
----- Begin Fatal Exception 14-Feb-2016 11:52:51 CST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 339 event: 359298
   [1] Running path 'p'
   [2] Calling event method for module ExTreeMaker/'framework'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: LHEEventProduct
Looking for module label: externalLHEProducer
Looking for productInstanceName:

   Additional Info:                          
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

I'm waiting for the rest of the prod to be more advanced before to confirm if it's the only trouble !

### PR DESCRIPTION
**Pull request by blinkseb**

### CODE REVIEW

**Comment by OlivierBondu** [comment]
oops, my bad then, many thanks !

**Comment by blinkseb** [comment]
Nah it's weird, in your PR the code was in the right place and I have not touch it, so something fishy must have happened when I rebased :question:

**Comment by blinkseb** [comment]
please test

**Comment by OlivierBondu** [comment]
```
Check if trees are equals
-------------------------------------------------------------------------------
/var/jenkins/workspace/Framework/CMSSW/CMSSW_7_4_15/src/cp3_llbb/Framework/bin/testFrameworkOutput.cc:101
...............................................................................

/var/jenkins/workspace/Framework/CMSSW/CMSSW_7_4_15/src/cp3_llbb/Framework/bin/testFrameworkOutput.cc:96: FAILED:
  REQUIRE( ref_sha == test_sha )
with expansion:
  "0c08d10e05bb6c7c9d08443e18a11abe861419aa230d72fd342f9f736b5f9547"
  ==
  "2e83fcc2081e7e8f2da9bccb743e70b7c7e19a30b752155d3ede89b99400a961"
with message:
  [Event 1] Checking branches event_ht of type 

===============================================================================
test cases:    1 |    0 passed | 1 failed
assertions: 1844 | 1843 passed | 1 failed

Output file does not match reference file: status 1
status = 256

---> test Testcp3_llbbFramework had ERRORS
```

That's unexpected no ? for MC it should be the same, for the data it should not be filled...

**Comment by blinkseb** [comment]
It is indeed totally unexpected!

**Comment by blinkseb** [comment]
So trees are indeed different, only because I've changed the code a bit to avoid using a temporary variable. There's in some case some rounding differences between float and double:

Ref:

```
HT = 306.002960205078125
```

With this PR:

```
HT = 306.00299072265625
```

Yep, it's different :laughing: I'll update the trees

**Comment by blinkseb** [comment]
Good to merge

**Pull request merged**
