### PR TITLE
[74X] Force trigger legs efficiency fluctuation to be between 0 and 1

### PR DESCRIPTION
**Pull request by BrieucF**
They provide errors allowing to have negative and bigger than 100% efficiencies once applying the down/up fluctuation.

### CODE REVIEW

**Comment by blinkseb** [comment]
Thanks! I've made some tests, and you'll also need also clamp the resulting trigger efficiency up or down as they will sometimes be greater than 1 or less than 0.

**Comment by BrieucF** [comment]
Indeed, this is again done at the analyzer level, once the fluctuation is obtain from full formula. BTW, we should maybe also do it when we extrapolate SF outside of the provided range (doubling the error).

**Comment by blinkseb** [comment]
You mean efficiency here and not SF right? If so, then I agree :+1: Otherwise, SF can be greater than one, so it's not an issue in this case.

**Comment by BrieucF** [comment]
Sure, I meant efficiencies, sorry for the typo ;-)

**Pull request merged**
